### ISSUE TITLE
loading spiral of doom

### ISSUE THREAD

**Issue by ahdinosaur** [mmckegg/patchwork-next#3]
after not using `patchwork-next` for a while but keeping it open, then loading a new page or re-loading the main feed causes there to be an infinite loading spiral of doom, plus this is logged to the node console:

```
TypeError: Cannot read property 'childNodes' of null
    at replace (/home/dinosaur/repos/mmckegg/patchwork-next/node_modules/mutant/html-element.js:142:21)
    at Array.Binding.update (/home/dinosaur/repos/mmckegg/patchwork-next/node_modules/mutant/html-element.js:256:7)
    at Function.Observable.observable.set (/home/dinosaur/repos/mmckegg/patchwork-next/node_modules/mutant/value.js:12:25)
    at /home/dinosaur/repos/mmckegg/patchwork-next/node_modules/mutant/dict-to-collection.js:26:24
    at Object.computed.onListen.lazy (/home/dinosaur/repos/mmckegg/patchwork-next/node_modules/mutant/computed.js:211:12)
    at Object.update (/home/dinosaur/repos/mmckegg/patchwork-next/node_modules/mutant/computed.js:125:42)
    at Object.updateNow (/home/dinosaur/repos/mmckegg/patchwork-next/node_modules/mutant/computed.js:179:14)
    at Object.onUpdate (/home/dinosaur/repos/mmckegg/patchwork-next/node_modules/mutant/computed.js:166:12)
    at broadcast (/home/dinosaur/repos/mmckegg/patchwork-next/node_modules/mutant/lib/lazy-watcher.js:111:27)
    at Object.broadcast (/home/dinosaur/repos/mmckegg/patchwork-next/node_modules/mutant/lib/lazy-watcher.js:24:9)
```

**Comment by mmckegg** [comment]
yep! I've been getting that. I think it's the same issue we used to have, but I've changed the timeout on old pages from 30 mins down to 5 mins, so it's happening quicker.

Just getting stuck into the bug now. Think it's mutant doing something stupid when an item is removed from a dictionary in the middle.
