### ISSUE TITLE
Upgrade problems

### ISSUE THREAD

**Issue by bhaugen** [mmckegg/patchwork-next#4]
Did: 
```
git pull
npm install
npm start
```
An electron window came up, but never populated with any content.

From the terminal:
```
> patchwork-next@3.0.3 start /home/bob/patchwork-next
> electron index.js

Log level: notice
RELOAD INDEX: {"version":13,"since":1488299695116}
Error: Cannot find module 'electron-spellchecker'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/bob/patchwork-next/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bob/patchwork-next/lib/context-menu-and-spellcheck.js:2:68)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
Connected sbot.ktorn.com:8008:@BzMp3eRNjPUonwRd/0loT3KaRKIMFx7ZOZQE1F+XDug=.ed25519
Connected queen.ansuz.xyz:8008:@80U8ErlN820R3Ut+h6TOP4iWEMkQx52xE0cYErmR3Wg=.ed25519
Connected eu6.woll-e.net:8008:@H1j0ybFVLhnfYx47DekUadGysJPOaOAWtKFx5Le4+hQ=.ed25519
Connected sbot.ktorn.com:8008:@BzMp3eRNjPUonwRd/0loT3KaRKIMFx7ZOZQE1F+XDug=.ed25519
```

And there it sat, for maybe 5 minutes, before I killed it and posted this issue.

**Comment by mmckegg** [comment]
@bhaugen seems like `npm install` isn't completing properly. Maybe you need to install some dependencies for the new spellcheck.

Try running:

```shell
sudo apt-get install libxext-dev libxtst-dev libxkbfile-dev
```

And then run `npm install` again.

**Comment by bhaugen** [comment]
```
sudo apt-get install libxext-dev libxtst-dev libxkbfile-dev

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxext-dev is already the newest version.
libxext-dev set to manually installed.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libxtst-dev : Depends: libxi-dev but it is not going to be installed
               Depends: x11proto-record-dev (>= 1.13.99.1) but it is not going to be installed
 linux-headers-generic : Depends: linux-headers-3.2.0-123-generic but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```
Tried that suggestion, but ran into a problem: 
```
error creating directory `./usr/src/linux-headers-3.2.0-123-generic/include/config/vmware': No space left on device
No apport report written because the error message indicates a disk full error
```
So this will take awhile...
